openapi: '3.0.3'
info:
  title: Microservices book
  description: |
    API for Airplane Management System
  version: '1.0'
servers:
  - url: https://localhost:8123
    description: Local server
paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
  /reservations/{reservation_id}:
    put:
      summary: Book or re-book a reservation
      description: |
        Example: #TODO
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Unique id of reservation being created or changed
          schema:
            type: string
          example: d2783fc5-0fee

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                outbond:
                  type: object
                  properties:
                    flight_num:
                      type:
                        string
                      example:
                        "AA 253"
                    flight_date:
                      type:
                        string
                      example:
                        "2019-12-31T08:01:00"
                    seats:
                      type: array
                      items:
                        type:
                          string
                returning:
                  type: object
                  properties:
                    flight_num:
                      type:
                        string
                      example:
                        "AA 254"
                    flight_date:
                      type:
                        string
                      example:
                        "2020-01-07T14:05:00"
                    seats:
                      type: array
                      items:
                        type: string
                        example: [
                            {
                              "outbond": {
                                flight_num: "AA 253",
                                flight_date: "2019-12-31T08:01:00",
                                seats: [
                                  "9C"
                                ]
                              },
                              "returning": {
                                flight_num: "AA 254",
                                flight_date: "2020-01-07T14:05:00",
                                seats: [
                                  "10A"
                                ]
                              }
                            }
                        ]
      responses:
        '200':
          description: "Succesfull reservation"
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation_id:
                    type: string
                    description: some additional description
        '403':
          description: Seat(s) unavailable. Booking failed.
          content:
            application/json:
              schema:
                type: string
                description: detailed information
